export const PORT: string = process.env.PORT || "8000";

export const PLAYER_MAX_NUMBER: number = Number(process.env.PORT) || 6;

export const rareCardList: { name: string, cardURL: string, cardID: string }[] =
  [
    {name: "カオス・ソルジャー －開闢の使者－", cardURL: "4HZgkF5eTAsS", cardID: "4HZgkF5eTAsS-1"},
    {name: "カオス・ソルジャー －開闢の使者－", cardURL: "4HZgkF5eTAsS", cardID: "4HZgkF5eTAsS-2"},
    {name: "カオス・ソルジャー －開闢の使者－", cardURL: "4HZgkF5eTAsS", cardID: "4HZgkF5eTAsS-3"},
    {name: "氷結界の龍 トリシューラ", cardURL: "AHWIVNomv6qk", cardID: "AHWIVNomv6qk-1"},
    {name: "氷結界の龍 トリシューラ", cardURL: "AHWIVNomv6qk", cardID: "AHWIVNomv6qk-2"},
    {name: "氷結界の龍 トリシューラ", cardURL: "AHWIVNomv6qk", cardID: "AHWIVNomv6qk-3"}
  ];

export const monsterCardList: { name: string, cardURL: string, cardID: string }[] =
  [
    {name: "フォトン・スラッシャー", cardURL: "r3kzHcoM5fgy", cardID: "r3kzHcoM5fgy-1"},
    {name: "フォトン・スラッシャー", cardURL: "r3kzHcoM5fgy", cardID: "r3kzHcoM5fgy-2"},
    {name: "フォトン・スラッシャー", cardURL: "r3kzHcoM5fgy", cardID: "r3kzHcoM5fgy-3"},
    {name: "ジェネクス・ニュートロン", cardURL: "pCMWKzptYyX2", cardID: "pCMWKzptYyX2-1"},
    {name: "ジェネクス・ニュートロン", cardURL: "pCMWKzptYyX2", cardID: "pCMWKzptYyX2-2"},
    {name: "ジェネクス・ニュートロン", cardURL: "pCMWKzptYyX2", cardID: "pCMWKzptYyX2-3"},
    {name: "矮星竜プラネター", cardURL: "fQ2qyWtK7j7a", cardID: "fQ2qyWtK7j7a-1"},
    {name: "矮星竜プラネター", cardURL: "fQ2qyWtK7j7a", cardID: "fQ2qyWtK7j7a-2"},
    {name: "矮星竜プラネター", cardURL: "fQ2qyWtK7j7a", cardID: "fQ2qyWtK7j7a-3"},
    {name: "ライトロード・アサシン ライデン", cardURL: "kqhLDWYrvhhk", cardID: "kqhLDWYrvhhk-1"},
    {name: "ライトロード・アサシン ライデン", cardURL: "kqhLDWYrvhhk", cardID: "kqhLDWYrvhhk-2"},
    {name: "ライトロード・アサシン ライデン", cardURL: "kqhLDWYrvhhk", cardID: "kqhLDWYrvhhk-3"},
    {name: "ライトロード・マジシャン ライラ", cardURL: "otYpurbA-BkB", cardID: "otYpurbA-BkB-1"},
    {name: "ライトロード・マジシャン ライラ", cardURL: "otYpurbA-BkB", cardID: "otYpurbA-BkB-2"},
    {name: "ライトロード・マジシャン ライラ", cardURL: "otYpurbA-BkB", cardID: "otYpurbA-BkB-3"},
    {name: "ライトロード・モンク エイリン", cardURL: "TQnrWxfF3pDB", cardID: "TQnrWxfF3pDB-1"},
    {name: "ライトロード・モンク エイリン", cardURL: "TQnrWxfF3pDB", cardID: "TQnrWxfF3pDB-2"},
    {name: "ライトロード・モンク エイリン", cardURL: "TQnrWxfF3pDB", cardID: "TQnrWxfF3pDB-3"},
    {name: "ライトロード・ハンター ライコウ", cardURL: "BXi3xFc1QbQA", cardID: "BXi3xFc1QbQA-1"},
    {name: "ライトロード・ハンター ライコウ", cardURL: "BXi3xFc1QbQA", cardID: "BXi3xFc1QbQA-2"},
    {name: "ライトロード・ハンター ライコウ", cardURL: "BXi3xFc1QbQA", cardID: "BXi3xFc1QbQA-3"},
    {name: "虹クリボー", cardURL: "IDj_yk25AxNF", cardID: "IDj_yk25AxNF-1"},
    {name: "虹クリボー", cardURL: "IDj_yk25AxNF", cardID: "IDj_yk25AxNF-2"},
    {name: "虹クリボー", cardURL: "IDj_yk25AxNF", cardID: "IDj_yk25AxNF-3"},
    {name: "エフェクト・ヴェーラー", cardURL: "tI75vNFy-IDy", cardID: "tI75vNFy-IDy-1"},
    {name: "エフェクト・ヴェーラー", cardURL: "tI75vNFy-IDy", cardID: "tI75vNFy-IDy-2"},
    {name: "エフェクト・ヴェーラー", cardURL: "tI75vNFy-IDy", cardID: "tI75vNFy-IDy-3"},
    {name: "巌征竜－レドックス", cardURL: "Xz84w8oIWac2", cardID: "Xz84w8oIWac2-1"},
    {name: "巌征竜－レドックス", cardURL: "Xz84w8oIWac2", cardID: "Xz84w8oIWac2-2"},
    {name: "巌征竜－レドックス", cardURL: "Xz84w8oIWac2", cardID: "Xz84w8oIWac2-3"},
    {name: "ゴブリンドバーグ", cardURL: "w-8eEg_xMmBM", cardID: "w-8eEg_xMmBM-1"},
    {name: "ゴブリンドバーグ", cardURL: "w-8eEg_xMmBM", cardID: "w-8eEg_xMmBM-2"},
    {name: "ゴブリンドバーグ", cardURL: "w-8eEg_xMmBM", cardID: "w-8eEg_xMmBM-3"},
    {name: "カメンレオン", cardURL: "9y8RxUvDx4ly", cardID: "9y8RxUvDx4ly-1"},
    {name: "カメンレオン", cardURL: "9y8RxUvDx4ly", cardID: "9y8RxUvDx4ly-2"},
    {name: "カメンレオン", cardURL: "9y8RxUvDx4ly", cardID: "9y8RxUvDx4ly-3"},
    {name: "ＴＧ ラッシュ・ライノ", cardURL: "ynGqqv0cfY_A", cardID: "ynGqqv0cfY_A-1"},
    {name: "ＴＧ ラッシュ・ライノ", cardURL: "ynGqqv0cfY_A", cardID: "ynGqqv0cfY_A-2"},
    {name: "ＴＧ ラッシュ・ライノ", cardURL: "ynGqqv0cfY_A", cardID: "ynGqqv0cfY_A-3"},
    {name: "トリオンの蟲惑魔", cardURL: "wO2y4UG_supM", cardID: "wO2y4UG_supM-1"},
    {name: "トリオンの蟲惑魔", cardURL: "wO2y4UG_supM", cardID: "wO2y4UG_supM-2"},
    {name: "トリオンの蟲惑魔", cardURL: "wO2y4UG_supM", cardID: "wO2y4UG_supM-3"},
    {name: "Ｘ－セイバー エアベルン", cardURL: "1CBfXa0pTwHU", cardID: "1CBfXa0pTwHU-1"},
    {name: "Ｘ－セイバー エアベルン", cardURL: "1CBfXa0pTwHU", cardID: "1CBfXa0pTwHU-2"},
    {name: "Ｘ－セイバー エアベルン", cardURL: "1CBfXa0pTwHU", cardID: "1CBfXa0pTwHU-3"},
    {name: "クレーンクレーン", cardURL: "gTCfgaW4T_1n", cardID: "gTCfgaW4T_1n-1"},
    {name: "クレーンクレーン", cardURL: "gTCfgaW4T_1n", cardID: "gTCfgaW4T_1n-2"},
    {name: "クレーンクレーン", cardURL: "gTCfgaW4T_1n", cardID: "gTCfgaW4T_1n-3"},
    {name: "工作列車シグナル・レッド", cardURL: "D4eTKeKQsLwM", cardID: "D4eTKeKQsLwM-1"},
    {name: "工作列車シグナル・レッド", cardURL: "D4eTKeKQsLwM", cardID: "D4eTKeKQsLwM-2"},
    {name: "工作列車シグナル・レッド", cardURL: "D4eTKeKQsLwM", cardID: "D4eTKeKQsLwM-3"},
    {name: "カードガンナー", cardURL: "R3x6Y057xHdN", cardID: "R3x6Y057xHdN-1"},
    {name: "カードガンナー", cardURL: "R3x6Y057xHdN", cardID: "R3x6Y057xHdN-2"},
    {name: "カードガンナー", cardURL: "R3x6Y057xHdN", cardID: "R3x6Y057xHdN-3"},
    {name: "ダンディライオン", cardURL: "apC4XWoNY9Y7", cardID: "apC4XWoNY9Y7-1"},
    {name: "ダンディライオン", cardURL: "apC4XWoNY9Y7", cardID: "apC4XWoNY9Y7-2"},
    {name: "ダンディライオン", cardURL: "apC4XWoNY9Y7", cardID: "apC4XWoNY9Y7-3"},
    {name: "ＴＧ ストライカー", cardURL: "NoBKUyJ_bvPA", cardID: "NoBKUyJ_bvPA-1"},
    {name: "ＴＧ ストライカー", cardURL: "NoBKUyJ_bvPA", cardID: "NoBKUyJ_bvPA-2"},
    {name: "ＴＧ ストライカー", cardURL: "NoBKUyJ_bvPA", cardID: "NoBKUyJ_bvPA-3"},
    {name: "メタモルポット", cardURL: "LdKqQDc_Cxll", cardID: "LdKqQDc_Cxll-1"},
    {name: "メタモルポット", cardURL: "LdKqQDc_Cxll", cardID: "LdKqQDc_Cxll-2"},
    {name: "メタモルポット", cardURL: "LdKqQDc_Cxll", cardID: "LdKqQDc_Cxll-3"},
    {name: "グローアップ・バルブ", cardURL: "k0VAOv2Z8i5k", cardID: "k0VAOv2Z8i5k-1"},
    {name: "グローアップ・バルブ", cardURL: "k0VAOv2Z8i5k", cardID: "k0VAOv2Z8i5k-2"},
    {name: "グローアップ・バルブ", cardURL: "k0VAOv2Z8i5k", cardID: "k0VAOv2Z8i5k-3"},
    {name: "勇炎星－エンショウ", cardURL: "VqxoetGD3gty", cardID: "VqxoetGD3gty-1"},
    {name: "勇炎星－エンショウ", cardURL: "VqxoetGD3gty", cardID: "VqxoetGD3gty-2"},
    {name: "勇炎星－エンショウ", cardURL: "VqxoetGD3gty", cardID: "VqxoetGD3gty-3"},
    {name: "暗炎星－ユウシ", cardURL: "uJc8WO3NwSgB", cardID: "uJc8WO3NwSgB-1"},
    {name: "暗炎星－ユウシ", cardURL: "uJc8WO3NwSgB", cardID: "uJc8WO3NwSgB-2"},
    {name: "暗炎星－ユウシ", cardURL: "uJc8WO3NwSgB", cardID: "uJc8WO3NwSgB-3"},
    {name: "フレムベル・ヘルドッグ", cardURL: "4cwyDQCrF7mS", cardID: "4cwyDQCrF7mS-1"},
    {name: "フレムベル・ヘルドッグ", cardURL: "4cwyDQCrF7mS", cardID: "4cwyDQCrF7mS-2"},
    {name: "フレムベル・ヘルドッグ", cardURL: "4cwyDQCrF7mS", cardID: "4cwyDQCrF7mS-3"},
    {name: "予言僧 チョウレン", cardURL: "zszgStGHyVjM", cardID: "zszgStGHyVjM-1"},
    {name: "予言僧 チョウレン", cardURL: "zszgStGHyVjM", cardID: "zszgStGHyVjM-2"},
    {name: "予言僧 チョウレン", cardURL: "zszgStGHyVjM", cardID: "zszgStGHyVjM-3"},
    {name: "ゲリラカイト", cardURL: "hj4-qdMHB6jU", cardID: "hj4-qdMHB6jU-1"},
    {name: "ゲリラカイト", cardURL: "hj4-qdMHB6jU", cardID: "hj4-qdMHB6jU-2"},
    {name: "ゲリラカイト", cardURL: "hj4-qdMHB6jU", cardID: "hj4-qdMHB6jU-3"},
    {name: "稲荷火", cardURL: "4spFvJMud7mS", cardID: "4spFvJMud7mS-1"},
    {name: "稲荷火", cardURL: "4spFvJMud7mS", cardID: "4spFvJMud7mS-2"},
    {name: "稲荷火", cardURL: "4spFvJMud7mS", cardID: "4spFvJMud7mS-3"},
    {name: "ジュラック・ヴェロー", cardURL: "3DYatUtpHj2X", cardID: "3DYatUtpHj2X-1"},
    {name: "ジュラック・ヴェロー", cardURL: "3DYatUtpHj2X", cardID: "3DYatUtpHj2X-2"},
    {name: "ジュラック・ヴェロー", cardURL: "3DYatUtpHj2X", cardID: "3DYatUtpHj2X-3"},
    {name: "ジュラック・グアイバ", cardURL: "d0tfKmVACLDN", cardID: "d0tfKmVACLDN-1"},
    {name: "ジュラック・グアイバ", cardURL: "d0tfKmVACLDN", cardID: "d0tfKmVACLDN-2"},
    {name: "ジュラック・グアイバ", cardURL: "d0tfKmVACLDN", cardID: "d0tfKmVACLDN-3"},
    {name: "ローンファイア・ブロッサム", cardURL: "0TcXgoblSpwp", cardID: "0TcXgoblSpwp-1"},
    {name: "ローンファイア・ブロッサム", cardURL: "0TcXgoblSpwp", cardID: "0TcXgoblSpwp-2"},
    {name: "ローンファイア・ブロッサム", cardURL: "0TcXgoblSpwp", cardID: "0TcXgoblSpwp-3"},
    {name: "氷帝メビウス", cardURL: "DUjYb6FfJ_CM", cardID: "DUjYb6FfJ_CM-1"},
    {name: "氷帝メビウス", cardURL: "DUjYb6FfJ_CM", cardID: "DUjYb6FfJ_CM-2"},
    {name: "氷帝メビウス", cardURL: "DUjYb6FfJ_CM", cardID: "DUjYb6FfJ_CM-3"},
    {name: "ジゴバイト", cardURL: "ABVwQYwsI6qk", cardID: "ABVwQYwsI6qk-1"},
    {name: "ジゴバイト", cardURL: "ABVwQYwsI6qk", cardID: "ABVwQYwsI6qk-2"},
    {name: "ジゴバイト", cardURL: "ABVwQYwsI6qk", cardID: "ABVwQYwsI6qk-3"},
    {name: "スノーマンイーター", cardURL: "MFdFFYDigkr2", cardID: "MFdFFYDigkr2-1"},
    {name: "スノーマンイーター", cardURL: "MFdFFYDigkr2", cardID: "MFdFFYDigkr2-2"},
    {name: "スノーマンイーター", cardURL: "MFdFFYDigkr2", cardID: "MFdFFYDigkr2-3"},
    {name: "黄泉ガエル", cardURL: "Zz0MJjFNkIwX", cardID: "Zz0MJjFNkIwX-1"},
    {name: "黄泉ガエル", cardURL: "Zz0MJjFNkIwX", cardID: "Zz0MJjFNkIwX-2"},
    {name: "黄泉ガエル", cardURL: "Zz0MJjFNkIwX", cardID: "Zz0MJjFNkIwX-3"},
    {name: "風帝ライザー", cardURL: "4YcQ-6xHm7mS", cardID: "4YcQ-6xHm7mS-1"},
    {name: "風帝ライザー", cardURL: "4YcQ-6xHm7mS", cardID: "4YcQ-6xHm7mS-2"},
    {name: "風帝ライザー", cardURL: "4YcQ-6xHm7mS", cardID: "4YcQ-6xHm7mS-3"},
    {name: "霞の谷のファルコン", cardURL: "rPma36pRzKey", cardID: "rPma36pRzKey-1"},
    {name: "霞の谷のファルコン", cardURL: "rPma36pRzKey", cardID: "rPma36pRzKey-2"},
    {name: "霞の谷のファルコン", cardURL: "rPma36pRzKey", cardID: "rPma36pRzKey-3"},
    {name: "裏風の精霊", cardURL: "KzNfACnXSWRa", cardID: "KzNfACnXSWRa-1"},
    {name: "裏風の精霊", cardURL: "KzNfACnXSWRa", cardID: "KzNfACnXSWRa-2"},
    {name: "裏風の精霊", cardURL: "KzNfACnXSWRa", cardID: "KzNfACnXSWRa-3"},
    {name: "幻獣機テザーウルフ", cardURL: "NFoPCbq8bchA", cardID: "NFoPCbq8bchA-1"},
    {name: "幻獣機テザーウルフ", cardURL: "NFoPCbq8bchA", cardID: "NFoPCbq8bchA-2"},
    {name: "幻獣機テザーウルフ", cardURL: "NFoPCbq8bchA", cardID: "NFoPCbq8bchA-3"},
    {name: "幻獣機ブラックファルコン", cardURL: "eowaageRRX1S", cardID: "eowaageRRX1S-1"},
    {name: "幻獣機ブラックファルコン", cardURL: "eowaageRRX1S", cardID: "eowaageRRX1S-2"},
    {name: "幻獣機ブラックファルコン", cardURL: "eowaageRRX1S", cardID: "eowaageRRX1S-3"},
    {name: "デブリ・ドラゴン", cardURL: "fgZQqGjj9qMa", cardID: "fgZQqGjj9qMa-1"},
    {name: "デブリ・ドラゴン", cardURL: "fgZQqGjj9qMa", cardID: "fgZQqGjj9qMa-2"},
    {name: "デブリ・ドラゴン", cardURL: "fgZQqGjj9qMa", cardID: "fgZQqGjj9qMa-3"},
    {name: "音響戦士サイザス", cardURL: "5RLST51RAKjX", cardID: "5RLST51RAKjX-1"},
    {name: "音響戦士サイザス", cardURL: "5RLST51RAKjX", cardID: "5RLST51RAKjX-2"},
    {name: "音響戦士サイザス", cardURL: "5RLST51RAKjX", cardID: "5RLST51RAKjX-3"},
    {name: "音響戦士ギータス", cardURL: "w4tg7Sr4Xo2M", cardID: "w4tg7Sr4Xo2M-1"},
    {name: "音響戦士ギータス", cardURL: "w4tg7Sr4Xo2M", cardID: "w4tg7Sr4Xo2M-2"},
    {name: "音響戦士ギータス", cardURL: "w4tg7Sr4Xo2M", cardID: "w4tg7Sr4Xo2M-3"},
    {name: "音響戦士ピアーノ", cardURL: "OtCu4Uzi2dVn", cardID: "OtCu4Uzi2dVn-1"},
    {name: "音響戦士ピアーノ", cardURL: "OtCu4Uzi2dVn", cardID: "OtCu4Uzi2dVn-2"},
    {name: "音響戦士ピアーノ", cardURL: "OtCu4Uzi2dVn", cardID: "OtCu4Uzi2dVn-3"},
    {name: "トラゴエディア", cardURL: "5VZHK1LPabfX", cardID: "5VZHK1LPabfX-1"},
    {name: "トラゴエディア", cardURL: "5VZHK1LPabfX", cardID: "5VZHK1LPabfX-2"},
    {name: "トラゴエディア", cardURL: "5VZHK1LPabfX", cardID: "5VZHK1LPabfX-3"},
    {name: "ダーク・シムルグ", cardURL: "HeW0Jac1PmlN", cardID: "HeW0Jac1PmlN-1"},
    {name: "ダーク・シムルグ", cardURL: "HeW0Jac1PmlN", cardID: "HeW0Jac1PmlN-2"},
    {name: "ダーク・シムルグ", cardURL: "HeW0Jac1PmlN", cardID: "HeW0Jac1PmlN-3"},
    {name: "カオス・ソーサラー", cardURL: "wRFcnMqY2upM", cardID: "wRFcnMqY2upM-1"},
    {name: "カオス・ソーサラー", cardURL: "wRFcnMqY2upM", cardID: "wRFcnMqY2upM-2"},
    {name: "カオス・ソーサラー", cardURL: "wRFcnMqY2upM", cardID: "wRFcnMqY2upM-3"},
    {name: "邪帝ガイウス", cardURL: "oLt3srQOzBkB", cardID: "oLt3srQOzBkB-1"},
    {name: "邪帝ガイウス", cardURL: "oLt3srQOzBkB", cardID: "oLt3srQOzBkB-2"},
    {name: "邪帝ガイウス", cardURL: "oLt3srQOzBkB", cardID: "oLt3srQOzBkB-3"},
    {name: "シャドール・ドラゴン", cardURL: "SnMR0cyyOTa7", cardID: "SnMR0cyyOTa7-1"},
    {name: "シャドール・ドラゴン", cardURL: "SnMR0cyyOTa7", cardID: "SnMR0cyyOTa7-2"},
    {name: "シャドール・ドラゴン", cardURL: "SnMR0cyyOTa7", cardID: "SnMR0cyyOTa7-3"},
    {name: "霊滅術師 カイクウ", cardURL: "65Rdh-BgNYLX", cardID: "65Rdh-BgNYLX-1"},
    {name: "霊滅術師 カイクウ", cardURL: "65Rdh-BgNYLX", cardID: "65Rdh-BgNYLX-2"},
    {name: "霊滅術師 カイクウ", cardURL: "65Rdh-BgNYLX", cardID: "65Rdh-BgNYLX-3"},
    {name: "黒き森のウィッチ", cardURL: "54ZdK39gyQIX", cardID: "54ZdK39gyQIX-1"},
    {name: "黒き森のウィッチ", cardURL: "54ZdK39gyQIX", cardID: "54ZdK39gyQIX-2"},
    {name: "黒き森のウィッチ", cardURL: "54ZdK39gyQIX", cardID: "54ZdK39gyQIX-3"},
    {name: "カゲトカゲ", cardURL: "-u9ibK5prlSp", cardID: "-u9ibK5prlSp-1"},
    {name: "カゲトカゲ", cardURL: "-u9ibK5prlSp", cardID: "-u9ibK5prlSp-2"},
    {name: "カゲトカゲ", cardURL: "-u9ibK5prlSp", cardID: "-u9ibK5prlSp-3"},
    {name: "Ａ・ジェネクス・バードマン", cardURL: "nz01_o57eHG7", cardID: "nz01_o57eHG7-1"},
    {name: "Ａ・ジェネクス・バードマン", cardURL: "nz01_o57eHG7", cardID: "nz01_o57eHG7-2"},
    {name: "Ａ・ジェネクス・バードマン", cardURL: "nz01_o57eHG7", cardID: "nz01_o57eHG7-3"},
    {name: "ＢＦ－疾風のゲイル", cardURL: "tUoz8Zz3D8Zy", cardID: "tUoz8Zz3D8Zy-1"},
    {name: "ＢＦ－疾風のゲイル", cardURL: "tUoz8Zz3D8Zy", cardID: "tUoz8Zz3D8Zy-2"},
    {name: "ＢＦ－疾風のゲイル", cardURL: "tUoz8Zz3D8Zy", cardID: "tUoz8Zz3D8Zy-3"},
    {name: "ＴＧ ワーウルフ", cardURL: "bTwnPudEt86a", cardID: "bTwnPudEt86a-1"},
    {name: "ＴＧ ワーウルフ", cardURL: "bTwnPudEt86a", cardID: "bTwnPudEt86a-2"},
    {name: "ＴＧ ワーウルフ", cardURL: "bTwnPudEt86a", cardID: "bTwnPudEt86a-3"},
    {name: "彼岸の悪鬼 スカラマリオン", cardURL: "Uxl8mpr84pz2", cardID: "Uxl8mpr84pz2-1"},
    {name: "彼岸の悪鬼 スカラマリオン", cardURL: "Uxl8mpr84pz2", cardID: "Uxl8mpr84pz2-2"},
    {name: "彼岸の悪鬼 スカラマリオン", cardURL: "Uxl8mpr84pz2", cardID: "Uxl8mpr84pz2-3"},
    {name: "クリッター", cardURL: "TNlhZPL93M0B", cardID: "TNlhZPL93M0B-1"},
    {name: "クリッター", cardURL: "TNlhZPL93M0B", cardID: "TNlhZPL93M0B-2"},
    {name: "クリッター", cardURL: "TNlhZPL93M0B", cardID: "TNlhZPL93M0B-3"},
    {name: "魔界発現世行きデスガイド", cardURL: "3wrrR_81R4BX", cardID: "3wrrR_81R4BX-1"},
    {name: "魔界発現世行きデスガイド", cardURL: "3wrrR_81R4BX", cardID: "3wrrR_81R4BX-2"},
    {name: "魔界発現世行きデスガイド", cardURL: "3wrrR_81R4BX", cardID: "3wrrR_81R4BX-3"},
    {name: "ゾンビキャリア", cardURL: "Gqu-l4LZhtbN", cardID: "Gqu-l4LZhtbN-1"},
    {name: "ゾンビキャリア", cardURL: "Gqu-l4LZhtbN", cardID: "Gqu-l4LZhtbN-2"},
    {name: "ゾンビキャリア", cardURL: "Gqu-l4LZhtbN", cardID: "Gqu-l4LZhtbN-3"},
    {name: "絶対王 バック・ジャック", cardURL: "UbinpEbv4pz2", cardID: "UbinpEbv4pz2-1"},
    {name: "絶対王 バック・ジャック", cardURL: "UbinpEbv4pz2", cardID: "UbinpEbv4pz2-2"},
    {name: "絶対王 バック・ジャック", cardURL: "UbinpEbv4pz2", cardID: "UbinpEbv4pz2-3"}
  ];

export const magicCardList: { name: string, cardURL: string, cardID: string }[] =
  [
    {name: "ブラック・ホール", cardURL: "iVIsWINQHhCU", cardID: "iVIsWINQHhCU-1"},
    {name: "ブラック・ホール", cardURL: "iVIsWINQHhCU", cardID: "iVIsWINQHhCU-2"},
    {name: "ブラック・ホール", cardURL: "iVIsWINQHhCU", cardID: "iVIsWINQHhCU-3"},
    {name: "大嵐", cardURL: "T1Tr04WCwUZB", cardID: "T1Tr04WCwUZB-1"},
    {name: "大嵐", cardURL: "T1Tr04WCwUZB", cardID: "T1Tr04WCwUZB-2"},
    {name: "大嵐", cardURL: "T1Tr04WCwUZB", cardID: "T1Tr04WCwUZB-3"}
  ];

export const trapCardList: { name: string, cardURL: string, cardID: string }[] =
  [
    {name: "聖なるバリア －ミラーフォース－", cardURL: "4Sq6hpEqdAsS", cardID: "4Sq6hpEqdAsS-1"},
    {name: "聖なるバリア －ミラーフォース－", cardURL: "4Sq6hpEqdAsS", cardID: "4Sq6hpEqdAsS-2"},
    {name: "聖なるバリア －ミラーフォース－", cardURL: "4Sq6hpEqdAsS", cardID: "4Sq6hpEqdAsS-3"},
    {name: "激流葬", cardURL: "8lTB9DmqJh1F", cardID: "8lTB9DmqJh1F-1"},
    {name: "激流葬", cardURL: "8lTB9DmqJh1F", cardID: "8lTB9DmqJh1F-2"},
    {name: "激流葬", cardURL: "8lTB9DmqJh1F", cardID: "8lTB9DmqJh1F-3"}
  ];