import {CARD_TYPE} from "./Enums";

const ExtraCardList: { name: string, cardURL: string, cardID: string, cardType: number}[] =
  [
    {name: "神樹の守護獣－牙王", cardURL: "-FVRiE2eyB2p", cardID: "-FVRiE2eyB2p-1", cardType: CARD_TYPE.EXTRA},
    {name: "神樹の守護獣－牙王", cardURL: "-FVRiE2eyB2p", cardID: "-FVRiE2eyB2p-2", cardType: CARD_TYPE.EXTRA},
    {name: "閃珖竜 スターダスト", cardURL: "o-nXFUC95yUB", cardID: "o-nXFUC95yUB-1", cardType: CARD_TYPE.EXTRA},
    {name: "閃珖竜 スターダスト", cardURL: "o-nXFUC95yUB", cardID: "o-nXFUC95yUB-2", cardType: CARD_TYPE.EXTRA},
    {name: "クリムゾン・ブレーダー", cardURL: "5FsS8MhiGbfX", cardID: "5FsS8MhiGbfX-1", cardType: CARD_TYPE.EXTRA},
    {name: "クリムゾン・ブレーダー", cardURL: "5FsS8MhiGbfX", cardID: "5FsS8MhiGbfX-2", cardType: CARD_TYPE.EXTRA},
    {name: "レッド・デーモンズ・ドラゴン", cardURL: "hC26eGJxyZfU", cardID: "hC26eGJxyZfU-1", cardType: CARD_TYPE.EXTRA},
    {name: "レッド・デーモンズ・ドラゴン", cardURL: "hC26eGJxyZfU", cardID: "hC26eGJxyZfU-2", cardType: CARD_TYPE.EXTRA},
    {name: "スクラップ・ドラゴン", cardURL: "UocEty4jWXh2", cardID: "UocEty4jWXh2-1", cardType: CARD_TYPE.EXTRA},
    {name: "スクラップ・ドラゴン", cardURL: "UocEty4jWXh2", cardID: "UocEty4jWXh2-2", cardType: CARD_TYPE.EXTRA},
    {name: "クリアウィング・シンクロ・ドラゴン", cardURL: "XKNudP-vjac2", cardID: "XKNudP-vjac2-1", cardType: CARD_TYPE.EXTRA},
    {name: "クリアウィング・シンクロ・ドラゴン", cardURL: "XKNudP-vjac2", cardID: "XKNudP-vjac2-2", cardType: CARD_TYPE.EXTRA},
    {name: "ブラック・ローズ・ドラゴン", cardURL: "UCP5n8VXepz2", cardID: "UCP5n8VXepz2-1", cardType: CARD_TYPE.EXTRA},
    {name: "ブラック・ローズ・ドラゴン", cardURL: "UCP5n8VXepz2", cardID: "UCP5n8VXepz2-2", cardType: CARD_TYPE.EXTRA},
    {name: "霞の谷の雷神鬼", cardURL: "TnjuQBfk3pDB", cardID: "TnjuQBfk3pDB-1", cardType: CARD_TYPE.EXTRA},
    {name: "霞の谷の雷神鬼", cardURL: "TnjuQBfk3pDB", cardID: "TnjuQBfk3pDB-2", cardType: CARD_TYPE.EXTRA},
    {name: "月華竜 ブラック・ローズ", cardURL: "nGwEX6M6Wdr7", cardID: "nGwEX6M6Wdr7-1", cardType: CARD_TYPE.EXTRA},
    {name: "月華竜 ブラック・ローズ", cardURL: "nGwEX6M6Wdr7", cardID: "nGwEX6M6Wdr7-2", cardType: CARD_TYPE.EXTRA},
    {name: "ＢＦ－星影のノートゥング", cardURL: "zLnavG54prIM", cardID: "zLnavG54prIM-1", cardType: CARD_TYPE.EXTRA},
    {name: "ＢＦ－星影のノートゥング", cardURL: "zLnavG54prIM", cardID: "zLnavG54prIM-2", cardType: CARD_TYPE.EXTRA},
    {name: "オリエント・ドラゴン", cardURL: "nvRuON6jWG_7", cardID: "nvRuON6jWG_7-1", cardType: CARD_TYPE.EXTRA},
    {name: "オリエント・ドラゴン", cardURL: "nvRuON6jWG_7", cardID: "nvRuON6jWG_7-2", cardType: CARD_TYPE.EXTRA},
    {name: "獣神ヴァルカン", cardURL: "gVnKz7qWT_1n", cardID: "gVnKz7qWT_1n-1", cardType: CARD_TYPE.EXTRA},
    {name: "獣神ヴァルカン", cardURL: "gVnKz7qWT_1n", cardID: "gVnKz7qWT_1n-2", cardType: CARD_TYPE.EXTRA},
    {name: "瑚之龍", cardURL: "brbh-JI_Fvxa", cardID: "brbh-JI_Fvxa-1", cardType: CARD_TYPE.EXTRA},
    {name: "瑚之龍", cardURL: "brbh-JI_Fvxa", cardID: "brbh-JI_Fvxa-2", cardType: CARD_TYPE.EXTRA},
    {name: "幻層の守護者アルマデス", cardURL: "4ZXRrfk7d2RS", cardID: "4ZXRrfk7d2RS-1", cardType: CARD_TYPE.EXTRA},
    {name: "幻層の守護者アルマデス", cardURL: "4ZXRrfk7d2RS", cardID: "4ZXRrfk7d2RS-2", cardType: CARD_TYPE.EXTRA},
    {name: "超重剣聖ムサ－Ｃ", cardURL: "9zDK_hrc6jky", cardID: "9zDK_hrc6jky-1", cardType: CARD_TYPE.EXTRA},
    {name: "超重剣聖ムサ－Ｃ", cardURL: "9zDK_hrc6jky", cardID: "9zDK_hrc6jky-2", cardType: CARD_TYPE.EXTRA},
    {name: "転生竜サンサーラ", cardURL: "VPLQNP9U3Wdy", cardID: "VPLQNP9U3Wdy-1", cardType: CARD_TYPE.EXTRA},
    {name: "転生竜サンサーラ", cardURL: "VPLQNP9U3Wdy", cardID: "VPLQNP9U3Wdy-2", cardType: CARD_TYPE.EXTRA},
    {name: "Ａ・Ｏ・Ｊ カタストル", cardURL: "Y_9FGjdrMV4n", cardID: "Y_9FGjdrMV4n-1", cardType: CARD_TYPE.EXTRA},
    {name: "Ａ・Ｏ・Ｊ カタストル", cardURL: "Y_9FGjdrMV4n", cardID: "Y_9FGjdrMV4n-2", cardType: CARD_TYPE.EXTRA},
    {name: "交響魔人マエストローク", cardURL: "0LDett8w7M-p", cardID: "0LDett8w7M-p-1", cardType: CARD_TYPE.EXTRA},
    {name: "交響魔人マエストローク", cardURL: "0LDett8w7M-p", cardID: "0LDett8w7M-p-2", cardType: CARD_TYPE.EXTRA},
    {name: "エヴォルカイザー・ラギア", cardURL: "SUvXDXv-Omy7", cardID: "SUvXDXv-Omy7-1", cardType: CARD_TYPE.EXTRA},
    {name: "エヴォルカイザー・ラギア", cardURL: "SUvXDXv-Omy7", cardID: "SUvXDXv-Omy7-2", cardType: CARD_TYPE.EXTRA},
    {name: "Ｎｏ.８０ 狂装覇王ラプソディ・イン・バーサーク", cardURL: "Ga2j3RlCztbN", cardID: "Ga2j3RlCztbN-1", cardType: CARD_TYPE.EXTRA},
    {name: "Ｎｏ.８０ 狂装覇王ラプソディ・イン・バーサーク", cardURL: "Ga2j3RlCztbN", cardID: "Ga2j3RlCztbN-2", cardType: CARD_TYPE.EXTRA},
    {name: "キングレムリン", cardURL: "cXC6fG1m_64F", cardID: "cXC6fG1m_64F-1", cardType: CARD_TYPE.EXTRA},
    {name: "キングレムリン", cardURL: "cXC6fG1m_64F", cardID: "cXC6fG1m_64F-2", cardType: CARD_TYPE.EXTRA},
    {name: "ラヴァルバル・チェイン", cardURL: "c6CQ_FJ3yZKF", cardID: "c6CQ_FJ3yZKF-1", cardType: CARD_TYPE.EXTRA},
    {name: "ラヴァルバル・チェイン", cardURL: "c6CQ_FJ3yZKF", cardID: "c6CQ_FJ3yZKF-2", cardType: CARD_TYPE.EXTRA},
    {name: "ギアギガント Ｘ", cardURL: "G2Jg2Q57P9gN", cardID: "G2Jg2Q57P9gN-1", cardType: CARD_TYPE.EXTRA},
    {name: "ギアギガント Ｘ", cardURL: "G2Jg2Q57P9gN", cardID: "G2Jg2Q57P9gN-2", cardType: CARD_TYPE.EXTRA},
    {name: "彼岸の旅人 ダンテ", cardURL: "w6Knu8kuXupM", cardID: "w6Knu8kuXupM-1", cardType: CARD_TYPE.EXTRA},
    {name: "彼岸の旅人 ダンテ", cardURL: "w6Knu8kuXupM", cardID: "w6Knu8kuXupM-2", cardType: CARD_TYPE.EXTRA},
    {name: "発条機雷ゼンマイン", cardURL: "BJ29zeiHQKqA", cardID: "BJ29zeiHQKqA-1", cardType: CARD_TYPE.EXTRA},
    {name: "発条機雷ゼンマイン", cardURL: "BJ29zeiHQKqA", cardID: "BJ29zeiHQKqA-2", cardType: CARD_TYPE.EXTRA},
    {name: "虚空海竜リヴァイエール", cardURL: "_d-CHxDmP6el", cardID: "_d-CHxDmP6el-1", cardType: CARD_TYPE.EXTRA},
    {name: "虚空海竜リヴァイエール", cardURL: "_d-CHxDmP6el", cardID: "_d-CHxDmP6el-2", cardType: CARD_TYPE.EXTRA},
    {name: "神騎セイントレア", cardURL: "2_yqxgNcc-Ak", cardID: "2_yqxgNcc-Ak-1", cardType: CARD_TYPE.EXTRA},
    {name: "神騎セイントレア", cardURL: "2_yqxgNcc-Ak", cardID: "2_yqxgNcc-Ak-2", cardType: CARD_TYPE.EXTRA}
  ];

export default ExtraCardList;