import {CARD_TYPE} from "./Enums";

const MagicCardList: { name: string, cardURL: string, cardID: string, cardType: number}[] =
  [
    {name: "増援", cardURL: "ol48NDQWzBkB", cardID: "ol48NDQWzBkB-1", cardType: CARD_TYPE.MAGIC},
    {name: "増援", cardURL: "ol48NDQWzBkB", cardID: "ol48NDQWzBkB-2", cardType: CARD_TYPE.MAGIC},
    {name: "増援", cardURL: "ol48NDQWzBkB", cardID: "ol48NDQWzBkB-3", cardType: CARD_TYPE.MAGIC},
    {name: "月の書", cardURL: "yphyCHweKY_A", cardID: "yphyCHweKY_A-1", cardType: CARD_TYPE.MAGIC},
    {name: "月の書", cardURL: "yphyCHweKY_A", cardID: "yphyCHweKY_A-2", cardType: CARD_TYPE.MAGIC},
    {name: "月の書", cardURL: "yphyCHweKY_A", cardID: "yphyCHweKY_A-3", cardType: CARD_TYPE.MAGIC},
    {name: "禁じられた聖杯", cardURL: "JWuTaHFB0CDl", cardID: "JWuTaHFB0CDl-1", cardType: CARD_TYPE.MAGIC},
    {name: "禁じられた聖杯", cardURL: "JWuTaHFB0CDl", cardID: "JWuTaHFB0CDl-2", cardType: CARD_TYPE.MAGIC},
    {name: "禁じられた聖杯", cardURL: "JWuTaHFB0CDl", cardID: "JWuTaHFB0CDl-3", cardType: CARD_TYPE.MAGIC},
    {name: "光の援軍", cardURL: "MD556oaUe2G2", cardID: "MD556oaUe2G2-1", cardType: CARD_TYPE.MAGIC},
    {name: "光の援軍", cardURL: "MD556oaUe2G2", cardID: "MD556oaUe2G2-2", cardType: CARD_TYPE.MAGIC},
    {name: "光の援軍", cardURL: "MD556oaUe2G2", cardID: "MD556oaUe2G2-3", cardType: CARD_TYPE.MAGIC},
    {name: "帝王の烈旋", cardURL: "U_keTOfO4pz2", cardID: "U_keTOfO4pz2-1", cardType: CARD_TYPE.MAGIC},
    {name: "帝王の烈旋", cardURL: "U_keTOfO4pz2", cardID: "U_keTOfO4pz2-2", cardType: CARD_TYPE.MAGIC},
    {name: "帝王の烈旋", cardURL: "U_keTOfO4pz2", cardID: "U_keTOfO4pz2-3", cardType: CARD_TYPE.MAGIC},
    {name: "禁じられた聖槍", cardURL: "vIR1VwC0LDVF", cardID: "vIR1VwC0LDVF-1", cardType: CARD_TYPE.MAGIC},
    {name: "禁じられた聖槍", cardURL: "vIR1VwC0LDVF", cardID: "vIR1VwC0LDVF-2", cardType: CARD_TYPE.MAGIC},
    {name: "禁じられた聖槍", cardURL: "vIR1VwC0LDVF", cardID: "vIR1VwC0LDVF-3", cardType: CARD_TYPE.MAGIC},
    {name: "炎舞－「天キ」", cardURL: "mNyYTcqWDAJB", cardID: "mNyYTcqWDAJB-1", cardType: CARD_TYPE.MAGIC},
    {name: "炎舞－「天キ」", cardURL: "mNyYTcqWDAJB", cardID: "mNyYTcqWDAJB-2", cardType: CARD_TYPE.MAGIC},
    {name: "炎舞－「天キ」", cardURL: "mNyYTcqWDAJB", cardID: "mNyYTcqWDAJB-3", cardType: CARD_TYPE.MAGIC},
    {name: "エネミーコントローラー", cardURL: "S1Lq2xkbjuX7", cardID: "S1Lq2xkbjuX7-1", cardType: CARD_TYPE.MAGIC},
    {name: "エネミーコントローラー", cardURL: "S1Lq2xkbjuX7", cardID: "S1Lq2xkbjuX7-2", cardType: CARD_TYPE.MAGIC},
    {name: "エネミーコントローラー", cardURL: "S1Lq2xkbjuX7", cardID: "S1Lq2xkbjuX7-3", cardType: CARD_TYPE.MAGIC},
    {name: "ビッグバン・シュート", cardURL: "90_lClso34ly", cardID: "90_lClso34ly-1", cardType: CARD_TYPE.MAGIC},
    {name: "ビッグバン・シュート", cardURL: "90_lClso34ly", cardID: "90_lClso34ly-2", cardType: CARD_TYPE.MAGIC},
    {name: "ビッグバン・シュート", cardURL: "90_lClso34ly", cardID: "90_lClso34ly-3", cardType: CARD_TYPE.MAGIC},
    {name: "炎舞－「玉衝」", cardURL: "2-jc5C_hvxyk", cardID: "2-jc5C_hvxyk-1", cardType: CARD_TYPE.MAGIC},
    {name: "炎舞－「玉衝」", cardURL: "2-jc5C_hvxyk", cardID: "2-jc5C_hvxyk-2", cardType: CARD_TYPE.MAGIC},
    {name: "炎舞－「玉衝」", cardURL: "2-jc5C_hvxyk", cardID: "2-jc5C_hvxyk-3", cardType: CARD_TYPE.MAGIC},
    {name: "強制転移", cardURL: "hjTEbBN5RZfU", cardID: "hjTEbBN5RZfU-1", cardType: CARD_TYPE.MAGIC},
    {name: "強制転移", cardURL: "hjTEbBN5RZfU", cardID: "hjTEbBN5RZfU-2", cardType: CARD_TYPE.MAGIC},
    {name: "強制転移", cardURL: "hjTEbBN5RZfU", cardID: "hjTEbBN5RZfU-3", cardType: CARD_TYPE.MAGIC},
    {name: "サイクロン", cardURL: "jVteCSgyGlnS", cardID: "jVteCSgyGlnS-1", cardType: CARD_TYPE.MAGIC},
    {name: "サイクロン", cardURL: "jVteCSgyGlnS", cardID: "jVteCSgyGlnS-2", cardType: CARD_TYPE.MAGIC},
    {name: "サイクロン", cardURL: "jVteCSgyGlnS", cardID: "jVteCSgyGlnS-3", cardType: CARD_TYPE.MAGIC},
    {name: "貪欲な壺", cardURL: "OTr22AdTmRmn", cardID: "OTr22AdTmRmn-1", cardType: CARD_TYPE.MAGIC},
    {name: "貪欲な壺", cardURL: "OTr22AdTmRmn", cardID: "OTr22AdTmRmn-2", cardType: CARD_TYPE.MAGIC},
    {name: "貪欲な壺", cardURL: "OTr22AdTmRmn", cardID: "OTr22AdTmRmn-3", cardType: CARD_TYPE.MAGIC},
    {name: "精神操作", cardURL: "ELIqu7nSsHHM", cardID: "ELIqu7nSsHHM-1", cardType: CARD_TYPE.MAGIC},
    {name: "精神操作", cardURL: "ELIqu7nSsHHM", cardID: "ELIqu7nSsHHM-2", cardType: CARD_TYPE.MAGIC},
    {name: "精神操作", cardURL: "ELIqu7nSsHHM", cardID: "ELIqu7nSsHHM-3", cardType: CARD_TYPE.MAGIC},
    {name: "ハリケーン", cardURL: "h_3k2dXzXZfU", cardID: "h_3k2dXzXZfU-1", cardType: CARD_TYPE.MAGIC},
    {name: "ハリケーン", cardURL: "h_3k2dXzXZfU", cardID: "h_3k2dXzXZfU-2", cardType: CARD_TYPE.MAGIC},
    {name: "ハリケーン", cardURL: "h_3k2dXzXZfU", cardID: "h_3k2dXzXZfU-3", cardType: CARD_TYPE.MAGIC},
    {name: "おろかな埋葬", cardURL: "XPOULVFaOSY2", cardID: "XPOULVFaOSY2-1", cardType: CARD_TYPE.MAGIC},
    {name: "おろかな埋葬", cardURL: "XPOULVFaOSY2", cardID: "XPOULVFaOSY2-2", cardType: CARD_TYPE.MAGIC},
    {name: "おろかな埋葬", cardURL: "XPOULVFaOSY2", cardID: "XPOULVFaOSY2-3", cardType: CARD_TYPE.MAGIC},
    {name: "地砕き", cardURL: "_9du-2av158l", cardID: "_9du-2av158l-1", cardType: CARD_TYPE.MAGIC},
    {name: "地砕き", cardURL: "_9du-2av158l", cardID: "_9du-2av158l-2", cardType: CARD_TYPE.MAGIC},
    {name: "地砕き", cardURL: "_9du-2av158l", cardID: "_9du-2av158l-3", cardType: CARD_TYPE.MAGIC},
    {name: "死者蘇生", cardURL: "eTMHGGy7HpES", cardID: "eTMHGGy7HpES-1", cardType: CARD_TYPE.MAGIC},
    {name: "死者蘇生", cardURL: "eTMHGGy7HpES", cardID: "eTMHGGy7HpES-2", cardType: CARD_TYPE.MAGIC},
    {name: "死者蘇生", cardURL: "eTMHGGy7HpES", cardID: "eTMHGGy7HpES-3", cardType: CARD_TYPE.MAGIC}
  ];

export default MagicCardList;