import {CARD_TYPE} from "./Enums";

const MonsterCardList: { name: string, cardURL: string, cardID: string, cardType: number}[] =
  [
    {name: "フォトン・スラッシャー", cardURL: "r3kzHcoM5fgy", cardID: "r3kzHcoM5fgy-1", cardType: CARD_TYPE.MONSTER},
    {name: "フォトン・スラッシャー", cardURL: "r3kzHcoM5fgy", cardID: "r3kzHcoM5fgy-2", cardType: CARD_TYPE.MONSTER},
    {name: "フォトン・スラッシャー", cardURL: "r3kzHcoM5fgy", cardID: "r3kzHcoM5fgy-3", cardType: CARD_TYPE.MONSTER},
    {name: "ジェネクス・ニュートロン", cardURL: "pCMWKzptYyX2", cardID: "pCMWKzptYyX2-1", cardType: CARD_TYPE.MONSTER},
    {name: "ジェネクス・ニュートロン", cardURL: "pCMWKzptYyX2", cardID: "pCMWKzptYyX2-2", cardType: CARD_TYPE.MONSTER},
    {name: "ジェネクス・ニュートロン", cardURL: "pCMWKzptYyX2", cardID: "pCMWKzptYyX2-3", cardType: CARD_TYPE.MONSTER},
    {name: "矮星竜プラネター", cardURL: "fQ2qyWtK7j7a", cardID: "fQ2qyWtK7j7a-1", cardType: CARD_TYPE.MONSTER},
    {name: "矮星竜プラネター", cardURL: "fQ2qyWtK7j7a", cardID: "fQ2qyWtK7j7a-2", cardType: CARD_TYPE.MONSTER},
    {name: "矮星竜プラネター", cardURL: "fQ2qyWtK7j7a", cardID: "fQ2qyWtK7j7a-3", cardType: CARD_TYPE.MONSTER},
    {name: "ライトロード・アサシン ライデン", cardURL: "kqhLDWYrvhhk", cardID: "kqhLDWYrvhhk-1", cardType: CARD_TYPE.MONSTER},
    {name: "ライトロード・アサシン ライデン", cardURL: "kqhLDWYrvhhk", cardID: "kqhLDWYrvhhk-2", cardType: CARD_TYPE.MONSTER},
    {name: "ライトロード・アサシン ライデン", cardURL: "kqhLDWYrvhhk", cardID: "kqhLDWYrvhhk-3", cardType: CARD_TYPE.MONSTER},
    {name: "ライトロード・マジシャン ライラ", cardURL: "otYpurbA-BkB", cardID: "otYpurbA-BkB-1", cardType: CARD_TYPE.MONSTER},
    {name: "ライトロード・マジシャン ライラ", cardURL: "otYpurbA-BkB", cardID: "otYpurbA-BkB-2", cardType: CARD_TYPE.MONSTER},
    {name: "ライトロード・マジシャン ライラ", cardURL: "otYpurbA-BkB", cardID: "otYpurbA-BkB-3", cardType: CARD_TYPE.MONSTER},
    {name: "ライトロード・モンク エイリン", cardURL: "TQnrWxfF3pDB", cardID: "TQnrWxfF3pDB-1", cardType: CARD_TYPE.MONSTER},
    {name: "ライトロード・モンク エイリン", cardURL: "TQnrWxfF3pDB", cardID: "TQnrWxfF3pDB-2", cardType: CARD_TYPE.MONSTER},
    {name: "ライトロード・モンク エイリン", cardURL: "TQnrWxfF3pDB", cardID: "TQnrWxfF3pDB-3", cardType: CARD_TYPE.MONSTER},
    {name: "ライトロード・ハンター ライコウ", cardURL: "BXi3xFc1QbQA", cardID: "BXi3xFc1QbQA-1", cardType: CARD_TYPE.MONSTER},
    {name: "ライトロード・ハンター ライコウ", cardURL: "BXi3xFc1QbQA", cardID: "BXi3xFc1QbQA-2", cardType: CARD_TYPE.MONSTER},
    {name: "ライトロード・ハンター ライコウ", cardURL: "BXi3xFc1QbQA", cardID: "BXi3xFc1QbQA-3", cardType: CARD_TYPE.MONSTER},
    {name: "虹クリボー", cardURL: "IDj_yk25AxNF", cardID: "IDj_yk25AxNF-1", cardType: CARD_TYPE.MONSTER},
    {name: "虹クリボー", cardURL: "IDj_yk25AxNF", cardID: "IDj_yk25AxNF-2", cardType: CARD_TYPE.MONSTER},
    {name: "虹クリボー", cardURL: "IDj_yk25AxNF", cardID: "IDj_yk25AxNF-3", cardType: CARD_TYPE.MONSTER},
    {name: "エフェクト・ヴェーラー", cardURL: "tI75vNFy-IDy", cardID: "tI75vNFy-IDy-1", cardType: CARD_TYPE.MONSTER},
    {name: "エフェクト・ヴェーラー", cardURL: "tI75vNFy-IDy", cardID: "tI75vNFy-IDy-2", cardType: CARD_TYPE.MONSTER},
    {name: "エフェクト・ヴェーラー", cardURL: "tI75vNFy-IDy", cardID: "tI75vNFy-IDy-3", cardType: CARD_TYPE.MONSTER},
    {name: "巌征竜－レドックス", cardURL: "Xz84w8oIWac2", cardID: "Xz84w8oIWac2-1", cardType: CARD_TYPE.MONSTER},
    {name: "巌征竜－レドックス", cardURL: "Xz84w8oIWac2", cardID: "Xz84w8oIWac2-2", cardType: CARD_TYPE.MONSTER},
    {name: "巌征竜－レドックス", cardURL: "Xz84w8oIWac2", cardID: "Xz84w8oIWac2-3", cardType: CARD_TYPE.MONSTER},
    {name: "ゴブリンドバーグ", cardURL: "w-8eEg_xMmBM", cardID: "w-8eEg_xMmBM-1", cardType: CARD_TYPE.MONSTER},
    {name: "ゴブリンドバーグ", cardURL: "w-8eEg_xMmBM", cardID: "w-8eEg_xMmBM-2", cardType: CARD_TYPE.MONSTER},
    {name: "ゴブリンドバーグ", cardURL: "w-8eEg_xMmBM", cardID: "w-8eEg_xMmBM-3", cardType: CARD_TYPE.MONSTER},
    {name: "カメンレオン", cardURL: "9y8RxUvDx4ly", cardID: "9y8RxUvDx4ly-1", cardType: CARD_TYPE.MONSTER},
    {name: "カメンレオン", cardURL: "9y8RxUvDx4ly", cardID: "9y8RxUvDx4ly-2", cardType: CARD_TYPE.MONSTER},
    {name: "カメンレオン", cardURL: "9y8RxUvDx4ly", cardID: "9y8RxUvDx4ly-3", cardType: CARD_TYPE.MONSTER},
    {name: "ＴＧ ラッシュ・ライノ", cardURL: "ynGqqv0cfY_A", cardID: "ynGqqv0cfY_A-1", cardType: CARD_TYPE.MONSTER},
    {name: "ＴＧ ラッシュ・ライノ", cardURL: "ynGqqv0cfY_A", cardID: "ynGqqv0cfY_A-2", cardType: CARD_TYPE.MONSTER},
    {name: "ＴＧ ラッシュ・ライノ", cardURL: "ynGqqv0cfY_A", cardID: "ynGqqv0cfY_A-3", cardType: CARD_TYPE.MONSTER},
    {name: "トリオンの蟲惑魔", cardURL: "wO2y4UG_supM", cardID: "wO2y4UG_supM-1", cardType: CARD_TYPE.MONSTER},
    {name: "トリオンの蟲惑魔", cardURL: "wO2y4UG_supM", cardID: "wO2y4UG_supM-2", cardType: CARD_TYPE.MONSTER},
    {name: "トリオンの蟲惑魔", cardURL: "wO2y4UG_supM", cardID: "wO2y4UG_supM-3", cardType: CARD_TYPE.MONSTER},
    {name: "Ｘ－セイバー エアベルン", cardURL: "1CBfXa0pTwHU", cardID: "1CBfXa0pTwHU-1", cardType: CARD_TYPE.MONSTER},
    {name: "Ｘ－セイバー エアベルン", cardURL: "1CBfXa0pTwHU", cardID: "1CBfXa0pTwHU-2", cardType: CARD_TYPE.MONSTER},
    {name: "Ｘ－セイバー エアベルン", cardURL: "1CBfXa0pTwHU", cardID: "1CBfXa0pTwHU-3", cardType: CARD_TYPE.MONSTER},
    {name: "クレーンクレーン", cardURL: "gTCfgaW4T_1n", cardID: "gTCfgaW4T_1n-1", cardType: CARD_TYPE.MONSTER},
    {name: "クレーンクレーン", cardURL: "gTCfgaW4T_1n", cardID: "gTCfgaW4T_1n-2", cardType: CARD_TYPE.MONSTER},
    {name: "クレーンクレーン", cardURL: "gTCfgaW4T_1n", cardID: "gTCfgaW4T_1n-3", cardType: CARD_TYPE.MONSTER},
    {name: "工作列車シグナル・レッド", cardURL: "D4eTKeKQsLwM", cardID: "D4eTKeKQsLwM-1", cardType: CARD_TYPE.MONSTER},
    {name: "工作列車シグナル・レッド", cardURL: "D4eTKeKQsLwM", cardID: "D4eTKeKQsLwM-2", cardType: CARD_TYPE.MONSTER},
    {name: "工作列車シグナル・レッド", cardURL: "D4eTKeKQsLwM", cardID: "D4eTKeKQsLwM-3", cardType: CARD_TYPE.MONSTER},
    {name: "カードガンナー", cardURL: "R3x6Y057xHdN", cardID: "R3x6Y057xHdN-1", cardType: CARD_TYPE.MONSTER},
    {name: "カードガンナー", cardURL: "R3x6Y057xHdN", cardID: "R3x6Y057xHdN-2", cardType: CARD_TYPE.MONSTER},
    {name: "カードガンナー", cardURL: "R3x6Y057xHdN", cardID: "R3x6Y057xHdN-3", cardType: CARD_TYPE.MONSTER},
    {name: "ダンディライオン", cardURL: "apC4XWoNY9Y7", cardID: "apC4XWoNY9Y7-1", cardType: CARD_TYPE.MONSTER},
    {name: "ダンディライオン", cardURL: "apC4XWoNY9Y7", cardID: "apC4XWoNY9Y7-2", cardType: CARD_TYPE.MONSTER},
    {name: "ダンディライオン", cardURL: "apC4XWoNY9Y7", cardID: "apC4XWoNY9Y7-3", cardType: CARD_TYPE.MONSTER},
    {name: "ＴＧ ストライカー", cardURL: "NoBKUyJ_bvPA", cardID: "NoBKUyJ_bvPA-1", cardType: CARD_TYPE.MONSTER},
    {name: "ＴＧ ストライカー", cardURL: "NoBKUyJ_bvPA", cardID: "NoBKUyJ_bvPA-2", cardType: CARD_TYPE.MONSTER},
    {name: "ＴＧ ストライカー", cardURL: "NoBKUyJ_bvPA", cardID: "NoBKUyJ_bvPA-3", cardType: CARD_TYPE.MONSTER},
    {name: "メタモルポット", cardURL: "LdKqQDc_Cxll", cardID: "LdKqQDc_Cxll-1", cardType: CARD_TYPE.MONSTER},
    {name: "メタモルポット", cardURL: "LdKqQDc_Cxll", cardID: "LdKqQDc_Cxll-2", cardType: CARD_TYPE.MONSTER},
    {name: "メタモルポット", cardURL: "LdKqQDc_Cxll", cardID: "LdKqQDc_Cxll-3", cardType: CARD_TYPE.MONSTER},
    {name: "グローアップ・バルブ", cardURL: "k0VAOv2Z8i5k", cardID: "k0VAOv2Z8i5k-1", cardType: CARD_TYPE.MONSTER},
    {name: "グローアップ・バルブ", cardURL: "k0VAOv2Z8i5k", cardID: "k0VAOv2Z8i5k-2", cardType: CARD_TYPE.MONSTER},
    {name: "グローアップ・バルブ", cardURL: "k0VAOv2Z8i5k", cardID: "k0VAOv2Z8i5k-3", cardType: CARD_TYPE.MONSTER},
    {name: "勇炎星－エンショウ", cardURL: "VqxoetGD3gty", cardID: "VqxoetGD3gty-1", cardType: CARD_TYPE.MONSTER},
    {name: "勇炎星－エンショウ", cardURL: "VqxoetGD3gty", cardID: "VqxoetGD3gty-2", cardType: CARD_TYPE.MONSTER},
    {name: "勇炎星－エンショウ", cardURL: "VqxoetGD3gty", cardID: "VqxoetGD3gty-3", cardType: CARD_TYPE.MONSTER},
    {name: "暗炎星－ユウシ", cardURL: "uJc8WO3NwSgB", cardID: "uJc8WO3NwSgB-1", cardType: CARD_TYPE.MONSTER},
    {name: "暗炎星－ユウシ", cardURL: "uJc8WO3NwSgB", cardID: "uJc8WO3NwSgB-2", cardType: CARD_TYPE.MONSTER},
    {name: "暗炎星－ユウシ", cardURL: "uJc8WO3NwSgB", cardID: "uJc8WO3NwSgB-3", cardType: CARD_TYPE.MONSTER},
    {name: "フレムベル・ヘルドッグ", cardURL: "4cwyDQCrF7mS", cardID: "4cwyDQCrF7mS-1", cardType: CARD_TYPE.MONSTER},
    {name: "フレムベル・ヘルドッグ", cardURL: "4cwyDQCrF7mS", cardID: "4cwyDQCrF7mS-2", cardType: CARD_TYPE.MONSTER},
    {name: "フレムベル・ヘルドッグ", cardURL: "4cwyDQCrF7mS", cardID: "4cwyDQCrF7mS-3", cardType: CARD_TYPE.MONSTER},
    {name: "予言僧 チョウレン", cardURL: "zszgStGHyVjM", cardID: "zszgStGHyVjM-1", cardType: CARD_TYPE.MONSTER},
    {name: "予言僧 チョウレン", cardURL: "zszgStGHyVjM", cardID: "zszgStGHyVjM-2", cardType: CARD_TYPE.MONSTER},
    {name: "予言僧 チョウレン", cardURL: "zszgStGHyVjM", cardID: "zszgStGHyVjM-3", cardType: CARD_TYPE.MONSTER},
    {name: "ゲリラカイト", cardURL: "hj4-qdMHB6jU", cardID: "hj4-qdMHB6jU-1", cardType: CARD_TYPE.MONSTER},
    {name: "ゲリラカイト", cardURL: "hj4-qdMHB6jU", cardID: "hj4-qdMHB6jU-2", cardType: CARD_TYPE.MONSTER},
    {name: "ゲリラカイト", cardURL: "hj4-qdMHB6jU", cardID: "hj4-qdMHB6jU-3", cardType: CARD_TYPE.MONSTER},
    {name: "稲荷火", cardURL: "4spFvJMud7mS", cardID: "4spFvJMud7mS-1", cardType: CARD_TYPE.MONSTER},
    {name: "稲荷火", cardURL: "4spFvJMud7mS", cardID: "4spFvJMud7mS-2", cardType: CARD_TYPE.MONSTER},
    {name: "稲荷火", cardURL: "4spFvJMud7mS", cardID: "4spFvJMud7mS-3", cardType: CARD_TYPE.MONSTER},
    {name: "ジュラック・ヴェロー", cardURL: "3DYatUtpHj2X", cardID: "3DYatUtpHj2X-1", cardType: CARD_TYPE.MONSTER},
    {name: "ジュラック・ヴェロー", cardURL: "3DYatUtpHj2X", cardID: "3DYatUtpHj2X-2", cardType: CARD_TYPE.MONSTER},
    {name: "ジュラック・ヴェロー", cardURL: "3DYatUtpHj2X", cardID: "3DYatUtpHj2X-3", cardType: CARD_TYPE.MONSTER},
    {name: "ジュラック・グアイバ", cardURL: "d0tfKmVACLDN", cardID: "d0tfKmVACLDN-1", cardType: CARD_TYPE.MONSTER},
    {name: "ジュラック・グアイバ", cardURL: "d0tfKmVACLDN", cardID: "d0tfKmVACLDN-2", cardType: CARD_TYPE.MONSTER},
    {name: "ジュラック・グアイバ", cardURL: "d0tfKmVACLDN", cardID: "d0tfKmVACLDN-3", cardType: CARD_TYPE.MONSTER},
    {name: "ローンファイア・ブロッサム", cardURL: "0TcXgoblSpwp", cardID: "0TcXgoblSpwp-1", cardType: CARD_TYPE.MONSTER},
    {name: "ローンファイア・ブロッサム", cardURL: "0TcXgoblSpwp", cardID: "0TcXgoblSpwp-2", cardType: CARD_TYPE.MONSTER},
    {name: "ローンファイア・ブロッサム", cardURL: "0TcXgoblSpwp", cardID: "0TcXgoblSpwp-3", cardType: CARD_TYPE.MONSTER},
    {name: "氷帝メビウス", cardURL: "DUjYb6FfJ_CM", cardID: "DUjYb6FfJ_CM-1", cardType: CARD_TYPE.MONSTER},
    {name: "氷帝メビウス", cardURL: "DUjYb6FfJ_CM", cardID: "DUjYb6FfJ_CM-2", cardType: CARD_TYPE.MONSTER},
    {name: "氷帝メビウス", cardURL: "DUjYb6FfJ_CM", cardID: "DUjYb6FfJ_CM-3", cardType: CARD_TYPE.MONSTER},
    {name: "ジゴバイト", cardURL: "ABVwQYwsI6qk", cardID: "ABVwQYwsI6qk-1", cardType: CARD_TYPE.MONSTER},
    {name: "ジゴバイト", cardURL: "ABVwQYwsI6qk", cardID: "ABVwQYwsI6qk-2", cardType: CARD_TYPE.MONSTER},
    {name: "ジゴバイト", cardURL: "ABVwQYwsI6qk", cardID: "ABVwQYwsI6qk-3", cardType: CARD_TYPE.MONSTER},
    {name: "スノーマンイーター", cardURL: "MFdFFYDigkr2", cardID: "MFdFFYDigkr2-1", cardType: CARD_TYPE.MONSTER},
    {name: "スノーマンイーター", cardURL: "MFdFFYDigkr2", cardID: "MFdFFYDigkr2-2", cardType: CARD_TYPE.MONSTER},
    {name: "スノーマンイーター", cardURL: "MFdFFYDigkr2", cardID: "MFdFFYDigkr2-3", cardType: CARD_TYPE.MONSTER},
    {name: "黄泉ガエル", cardURL: "Zz0MJjFNkIwX", cardID: "Zz0MJjFNkIwX-1", cardType: CARD_TYPE.MONSTER},
    {name: "黄泉ガエル", cardURL: "Zz0MJjFNkIwX", cardID: "Zz0MJjFNkIwX-2", cardType: CARD_TYPE.MONSTER},
    {name: "黄泉ガエル", cardURL: "Zz0MJjFNkIwX", cardID: "Zz0MJjFNkIwX-3", cardType: CARD_TYPE.MONSTER},
    {name: "風帝ライザー", cardURL: "4YcQ-6xHm7mS", cardID: "4YcQ-6xHm7mS-1", cardType: CARD_TYPE.MONSTER},
    {name: "風帝ライザー", cardURL: "4YcQ-6xHm7mS", cardID: "4YcQ-6xHm7mS-2", cardType: CARD_TYPE.MONSTER},
    {name: "風帝ライザー", cardURL: "4YcQ-6xHm7mS", cardID: "4YcQ-6xHm7mS-3", cardType: CARD_TYPE.MONSTER},
    {name: "霞の谷のファルコン", cardURL: "rPma36pRzKey", cardID: "rPma36pRzKey-1", cardType: CARD_TYPE.MONSTER},
    {name: "霞の谷のファルコン", cardURL: "rPma36pRzKey", cardID: "rPma36pRzKey-2", cardType: CARD_TYPE.MONSTER},
    {name: "霞の谷のファルコン", cardURL: "rPma36pRzKey", cardID: "rPma36pRzKey-3", cardType: CARD_TYPE.MONSTER},
    {name: "裏風の精霊", cardURL: "KzNfACnXSWRa", cardID: "KzNfACnXSWRa-1", cardType: CARD_TYPE.MONSTER},
    {name: "裏風の精霊", cardURL: "KzNfACnXSWRa", cardID: "KzNfACnXSWRa-2", cardType: CARD_TYPE.MONSTER},
    {name: "裏風の精霊", cardURL: "KzNfACnXSWRa", cardID: "KzNfACnXSWRa-3", cardType: CARD_TYPE.MONSTER},
    {name: "幻獣機テザーウルフ", cardURL: "NFoPCbq8bchA", cardID: "NFoPCbq8bchA-1", cardType: CARD_TYPE.MONSTER},
    {name: "幻獣機テザーウルフ", cardURL: "NFoPCbq8bchA", cardID: "NFoPCbq8bchA-2", cardType: CARD_TYPE.MONSTER},
    {name: "幻獣機テザーウルフ", cardURL: "NFoPCbq8bchA", cardID: "NFoPCbq8bchA-3", cardType: CARD_TYPE.MONSTER},
    {name: "幻獣機ブラックファルコン", cardURL: "eowaageRRX1S", cardID: "eowaageRRX1S-1", cardType: CARD_TYPE.MONSTER},
    {name: "幻獣機ブラックファルコン", cardURL: "eowaageRRX1S", cardID: "eowaageRRX1S-2", cardType: CARD_TYPE.MONSTER},
    {name: "幻獣機ブラックファルコン", cardURL: "eowaageRRX1S", cardID: "eowaageRRX1S-3", cardType: CARD_TYPE.MONSTER},
    {name: "デブリ・ドラゴン", cardURL: "fgZQqGjj9qMa", cardID: "fgZQqGjj9qMa-1", cardType: CARD_TYPE.MONSTER},
    {name: "デブリ・ドラゴン", cardURL: "fgZQqGjj9qMa", cardID: "fgZQqGjj9qMa-2", cardType: CARD_TYPE.MONSTER},
    {name: "デブリ・ドラゴン", cardURL: "fgZQqGjj9qMa", cardID: "fgZQqGjj9qMa-3", cardType: CARD_TYPE.MONSTER},
    {name: "音響戦士サイザス", cardURL: "5RLST51RAKjX", cardID: "5RLST51RAKjX-1", cardType: CARD_TYPE.MONSTER},
    {name: "音響戦士サイザス", cardURL: "5RLST51RAKjX", cardID: "5RLST51RAKjX-2", cardType: CARD_TYPE.MONSTER},
    {name: "音響戦士サイザス", cardURL: "5RLST51RAKjX", cardID: "5RLST51RAKjX-3", cardType: CARD_TYPE.MONSTER},
    {name: "音響戦士ギータス", cardURL: "w4tg7Sr4Xo2M", cardID: "w4tg7Sr4Xo2M-1", cardType: CARD_TYPE.MONSTER},
    {name: "音響戦士ギータス", cardURL: "w4tg7Sr4Xo2M", cardID: "w4tg7Sr4Xo2M-2", cardType: CARD_TYPE.MONSTER},
    {name: "音響戦士ギータス", cardURL: "w4tg7Sr4Xo2M", cardID: "w4tg7Sr4Xo2M-3", cardType: CARD_TYPE.MONSTER},
    {name: "音響戦士ピアーノ", cardURL: "OtCu4Uzi2dVn", cardID: "OtCu4Uzi2dVn-1", cardType: CARD_TYPE.MONSTER},
    {name: "音響戦士ピアーノ", cardURL: "OtCu4Uzi2dVn", cardID: "OtCu4Uzi2dVn-2", cardType: CARD_TYPE.MONSTER},
    {name: "音響戦士ピアーノ", cardURL: "OtCu4Uzi2dVn", cardID: "OtCu4Uzi2dVn-3", cardType: CARD_TYPE.MONSTER},
    {name: "トラゴエディア", cardURL: "5VZHK1LPabfX", cardID: "5VZHK1LPabfX-1", cardType: CARD_TYPE.MONSTER},
    {name: "トラゴエディア", cardURL: "5VZHK1LPabfX", cardID: "5VZHK1LPabfX-2", cardType: CARD_TYPE.MONSTER},
    {name: "トラゴエディア", cardURL: "5VZHK1LPabfX", cardID: "5VZHK1LPabfX-3", cardType: CARD_TYPE.MONSTER},
    {name: "ダーク・シムルグ", cardURL: "HeW0Jac1PmlN", cardID: "HeW0Jac1PmlN-1", cardType: CARD_TYPE.MONSTER},
    {name: "ダーク・シムルグ", cardURL: "HeW0Jac1PmlN", cardID: "HeW0Jac1PmlN-2", cardType: CARD_TYPE.MONSTER},
    {name: "ダーク・シムルグ", cardURL: "HeW0Jac1PmlN", cardID: "HeW0Jac1PmlN-3", cardType: CARD_TYPE.MONSTER},
    {name: "カオス・ソーサラー", cardURL: "wRFcnMqY2upM", cardID: "wRFcnMqY2upM-1", cardType: CARD_TYPE.MONSTER},
    {name: "カオス・ソーサラー", cardURL: "wRFcnMqY2upM", cardID: "wRFcnMqY2upM-2", cardType: CARD_TYPE.MONSTER},
    {name: "カオス・ソーサラー", cardURL: "wRFcnMqY2upM", cardID: "wRFcnMqY2upM-3", cardType: CARD_TYPE.MONSTER},
    {name: "邪帝ガイウス", cardURL: "oLt3srQOzBkB", cardID: "oLt3srQOzBkB-1", cardType: CARD_TYPE.MONSTER},
    {name: "邪帝ガイウス", cardURL: "oLt3srQOzBkB", cardID: "oLt3srQOzBkB-2", cardType: CARD_TYPE.MONSTER},
    {name: "邪帝ガイウス", cardURL: "oLt3srQOzBkB", cardID: "oLt3srQOzBkB-3", cardType: CARD_TYPE.MONSTER},
    {name: "シャドール・ドラゴン", cardURL: "SnMR0cyyOTa7", cardID: "SnMR0cyyOTa7-1", cardType: CARD_TYPE.MONSTER},
    {name: "シャドール・ドラゴン", cardURL: "SnMR0cyyOTa7", cardID: "SnMR0cyyOTa7-2", cardType: CARD_TYPE.MONSTER},
    {name: "シャドール・ドラゴン", cardURL: "SnMR0cyyOTa7", cardID: "SnMR0cyyOTa7-3", cardType: CARD_TYPE.MONSTER},
    {name: "霊滅術師 カイクウ", cardURL: "65Rdh-BgNYLX", cardID: "65Rdh-BgNYLX-1", cardType: CARD_TYPE.MONSTER},
    {name: "霊滅術師 カイクウ", cardURL: "65Rdh-BgNYLX", cardID: "65Rdh-BgNYLX-2", cardType: CARD_TYPE.MONSTER},
    {name: "霊滅術師 カイクウ", cardURL: "65Rdh-BgNYLX", cardID: "65Rdh-BgNYLX-3", cardType: CARD_TYPE.MONSTER},
    {name: "黒き森のウィッチ", cardURL: "54ZdK39gyQIX", cardID: "54ZdK39gyQIX-1", cardType: CARD_TYPE.MONSTER},
    {name: "黒き森のウィッチ", cardURL: "54ZdK39gyQIX", cardID: "54ZdK39gyQIX-2", cardType: CARD_TYPE.MONSTER},
    {name: "黒き森のウィッチ", cardURL: "54ZdK39gyQIX", cardID: "54ZdK39gyQIX-3", cardType: CARD_TYPE.MONSTER},
    {name: "カゲトカゲ", cardURL: "-u9ibK5prlSp", cardID: "-u9ibK5prlSp-1", cardType: CARD_TYPE.MONSTER},
    {name: "カゲトカゲ", cardURL: "-u9ibK5prlSp", cardID: "-u9ibK5prlSp-2", cardType: CARD_TYPE.MONSTER},
    {name: "カゲトカゲ", cardURL: "-u9ibK5prlSp", cardID: "-u9ibK5prlSp-3", cardType: CARD_TYPE.MONSTER},
    {name: "Ａ・ジェネクス・バードマン", cardURL: "nz01_o57eHG7", cardID: "nz01_o57eHG7-1", cardType: CARD_TYPE.MONSTER},
    {name: "Ａ・ジェネクス・バードマン", cardURL: "nz01_o57eHG7", cardID: "nz01_o57eHG7-2", cardType: CARD_TYPE.MONSTER},
    {name: "Ａ・ジェネクス・バードマン", cardURL: "nz01_o57eHG7", cardID: "nz01_o57eHG7-3", cardType: CARD_TYPE.MONSTER},
    {name: "ＢＦ－疾風のゲイル", cardURL: "tUoz8Zz3D8Zy", cardID: "tUoz8Zz3D8Zy-1", cardType: CARD_TYPE.MONSTER},
    {name: "ＢＦ－疾風のゲイル", cardURL: "tUoz8Zz3D8Zy", cardID: "tUoz8Zz3D8Zy-2", cardType: CARD_TYPE.MONSTER},
    {name: "ＢＦ－疾風のゲイル", cardURL: "tUoz8Zz3D8Zy", cardID: "tUoz8Zz3D8Zy-3", cardType: CARD_TYPE.MONSTER},
    {name: "ＴＧ ワーウルフ", cardURL: "bTwnPudEt86a", cardID: "bTwnPudEt86a-1", cardType: CARD_TYPE.MONSTER},
    {name: "ＴＧ ワーウルフ", cardURL: "bTwnPudEt86a", cardID: "bTwnPudEt86a-2", cardType: CARD_TYPE.MONSTER},
    {name: "ＴＧ ワーウルフ", cardURL: "bTwnPudEt86a", cardID: "bTwnPudEt86a-3", cardType: CARD_TYPE.MONSTER},
    {name: "彼岸の悪鬼 スカラマリオン", cardURL: "Uxl8mpr84pz2", cardID: "Uxl8mpr84pz2-1", cardType: CARD_TYPE.MONSTER},
    {name: "彼岸の悪鬼 スカラマリオン", cardURL: "Uxl8mpr84pz2", cardID: "Uxl8mpr84pz2-2", cardType: CARD_TYPE.MONSTER},
    {name: "彼岸の悪鬼 スカラマリオン", cardURL: "Uxl8mpr84pz2", cardID: "Uxl8mpr84pz2-3", cardType: CARD_TYPE.MONSTER},
    {name: "クリッター", cardURL: "TNlhZPL93M0B", cardID: "TNlhZPL93M0B-1", cardType: CARD_TYPE.MONSTER},
    {name: "クリッター", cardURL: "TNlhZPL93M0B", cardID: "TNlhZPL93M0B-2", cardType: CARD_TYPE.MONSTER},
    {name: "クリッター", cardURL: "TNlhZPL93M0B", cardID: "TNlhZPL93M0B-3", cardType: CARD_TYPE.MONSTER},
    {name: "魔界発現世行きデスガイド", cardURL: "3wrrR_81R4BX", cardID: "3wrrR_81R4BX-1", cardType: CARD_TYPE.MONSTER},
    {name: "魔界発現世行きデスガイド", cardURL: "3wrrR_81R4BX", cardID: "3wrrR_81R4BX-2", cardType: CARD_TYPE.MONSTER},
    {name: "魔界発現世行きデスガイド", cardURL: "3wrrR_81R4BX", cardID: "3wrrR_81R4BX-3", cardType: CARD_TYPE.MONSTER},
    {name: "ゾンビキャリア", cardURL: "Gqu-l4LZhtbN", cardID: "Gqu-l4LZhtbN-1", cardType: CARD_TYPE.MONSTER},
    {name: "ゾンビキャリア", cardURL: "Gqu-l4LZhtbN", cardID: "Gqu-l4LZhtbN-2", cardType: CARD_TYPE.MONSTER},
    {name: "ゾンビキャリア", cardURL: "Gqu-l4LZhtbN", cardID: "Gqu-l4LZhtbN-3", cardType: CARD_TYPE.MONSTER},
    {name: "絶対王 バック・ジャック", cardURL: "UbinpEbv4pz2", cardID: "UbinpEbv4pz2-1", cardType: CARD_TYPE.MONSTER},
    {name: "絶対王 バック・ジャック", cardURL: "UbinpEbv4pz2", cardID: "UbinpEbv4pz2-2", cardType: CARD_TYPE.MONSTER},
    {name: "絶対王 バック・ジャック", cardURL: "UbinpEbv4pz2", cardID: "UbinpEbv4pz2-3", cardType: CARD_TYPE.MONSTER}
  ];

export default MonsterCardList;