const RareCardList: { name: string, cardURL: string, cardID: string }[] =
  [
    {name: "カオス・ソルジャー －開闢の使者－", cardURL: "4HZgkF5eTAsS", cardID: "4HZgkF5eTAsS-1"},
    {name: "カオス・ソルジャー －開闢の使者－", cardURL: "4HZgkF5eTAsS", cardID: "4HZgkF5eTAsS-2"},
    {name: "カオス・ソルジャー －開闢の使者－", cardURL: "4HZgkF5eTAsS", cardID: "4HZgkF5eTAsS-3"},
    {name: "氷結界の龍 トリシューラ", cardURL: "AHWIVNomv6qk", cardID: "AHWIVNomv6qk-1"},
    {name: "氷結界の龍 トリシューラ", cardURL: "AHWIVNomv6qk", cardID: "AHWIVNomv6qk-2"},
    {name: "氷結界の龍 トリシューラ", cardURL: "AHWIVNomv6qk", cardID: "AHWIVNomv6qk-3"},
    {name: "冥府の使者ゴーズ", cardURL: "iCaifmLTp1-U", cardID: "iCaifmLTp1-U-1"},
    {name: "冥府の使者ゴーズ", cardURL: "iCaifmLTp1-U", cardID: "iCaifmLTp1-U-2"},
    {name: "冥府の使者ゴーズ", cardURL: "iCaifmLTp1-U", cardID: "iCaifmLTp1-U-3"},
    {name: "アストログラフ・マジシャン", cardURL: "3X8TyrGsuqpX", cardID: "3X8TyrGsuqpX-1"},
    {name: "アストログラフ・マジシャン", cardURL: "3X8TyrGsuqpX", cardID: "3X8TyrGsuqpX-2"},
    {name: "アストログラフ・マジシャン", cardURL: "3X8TyrGsuqpX", cardID: "3X8TyrGsuqpX-3"},
    {name: "マジェスペクター・ユニコーン", cardURL: "8lRGMkORsh1F", cardID: "8lRGMkORsh1F-1"},
    {name: "マジェスペクター・ユニコーン", cardURL: "8lRGMkORsh1F", cardID: "8lRGMkORsh1F-2"},
    {name: "マジェスペクター・ユニコーン", cardURL: "8lRGMkORsh1F", cardID: "8lRGMkORsh1F-3"},
    {name: "ブラック・ホール", cardURL: "iVIsWINQHhCU", cardID: "iVIsWINQHhCU-1"},
    {name: "ブラック・ホール", cardURL: "iVIsWINQHhCU", cardID: "iVIsWINQHhCU-2"},
    {name: "ブラック・ホール", cardURL: "iVIsWINQHhCU", cardID: "iVIsWINQHhCU-3"},
    {name: "大嵐", cardURL: "T1Tr04WCwUZB", cardID: "T1Tr04WCwUZB-1"},
    {name: "大嵐", cardURL: "T1Tr04WCwUZB", cardID: "T1Tr04WCwUZB-2"},
    {name: "大嵐", cardURL: "T1Tr04WCwUZB", cardID: "T1Tr04WCwUZB-3"},
    {name: "天使の施し", cardURL: "3WwyBFMDBeSX", cardID: "3WwyBFMDBeSX-1"},
    {name: "天使の施し", cardURL: "3WwyBFMDBeSX", cardID: "3WwyBFMDBeSX-2"},
    {name: "天使の施し", cardURL: "3WwyBFMDBeSX", cardID: "3WwyBFMDBeSX-3"},
    {name: "遺言状", cardURL: "gBlS4qH4o_1n", cardID: "gBlS4qH4o_1n-1"},
    {name: "遺言状", cardURL: "gBlS4qH4o_1n", cardID: "gBlS4qH4o_1n-2"},
    {name: "遺言状", cardURL: "gBlS4qH4o_1n", cardID: "gBlS4qH4o_1n-3"},
    {name: "聖なるバリア －ミラーフォース－", cardURL: "4Sq6hpEqdAsS", cardID: "4Sq6hpEqdAsS-1"},
    {name: "聖なるバリア －ミラーフォース－", cardURL: "4Sq6hpEqdAsS", cardID: "4Sq6hpEqdAsS-2"},
    {name: "聖なるバリア －ミラーフォース－", cardURL: "4Sq6hpEqdAsS", cardID: "4Sq6hpEqdAsS-3"},
    {name: "激流葬", cardURL: "8lTB9DmqJh1F", cardID: "8lTB9DmqJh1F-1"},
    {name: "激流葬", cardURL: "8lTB9DmqJh1F", cardID: "8lTB9DmqJh1F-2"},
    {name: "激流葬", cardURL: "8lTB9DmqJh1F", cardID: "8lTB9DmqJh1F-3"},
    {name: "神の宣告", cardURL: "vEkresPusEmF", cardID: "vEkresPusEmF-1"},
    {name: "神の宣告", cardURL: "vEkresPusEmF", cardID: "vEkresPusEmF-2"},
    {name: "神の宣告", cardURL: "vEkresPusEmF", cardID: "vEkresPusEmF-3"}
  ];

export default RareCardList;