import {CARD_TYPE} from "./Enums";

const TrapCardList: { name: string, cardURL: string, cardID: string, cardType: number}[] =
  [
    {name: "ブレイクスルー・スキル", cardURL: "89svv2KNJCEF", cardID: "89svv2KNJCEF-1", cardType: CARD_TYPE.TRAP},
    {name: "ブレイクスルー・スキル", cardURL: "89svv2KNJCEF", cardID: "89svv2KNJCEF-2", cardType: CARD_TYPE.TRAP},
    {name: "ブレイクスルー・スキル", cardURL: "89svv2KNJCEF", cardID: "89svv2KNJCEF-3", cardType: CARD_TYPE.TRAP},
    {name: "バージェストマ・カナディア", cardURL: "IDf7HPZbA-7F", cardID: "IDf7HPZbA-7F-1", cardType: CARD_TYPE.TRAP},
    {name: "バージェストマ・カナディア", cardURL: "IDf7HPZbA-7F", cardID: "IDf7HPZbA-7F-2", cardType: CARD_TYPE.TRAP},
    {name: "バージェストマ・カナディア", cardURL: "IDf7HPZbA-7F", cardID: "IDf7HPZbA-7F-3", cardType: CARD_TYPE.TRAP},
    {name: "量子猫", cardURL: "_xmFCN-n-3gl", cardID: "_xmFCN-n-3gl-1", cardType: CARD_TYPE.TRAP},
    {name: "量子猫", cardURL: "_xmFCN-n-3gl", cardID: "_xmFCN-n-3gl-2", cardType: CARD_TYPE.TRAP},
    {name: "量子猫", cardURL: "_xmFCN-n-3gl", cardID: "_xmFCN-n-3gl-3", cardType: CARD_TYPE.TRAP},
    {name: "強制脱出装置", cardURL: "UNkFXeq3jU52", cardID: "UNkFXeq3jU52-1", cardType: CARD_TYPE.TRAP},
    {name: "強制脱出装置", cardURL: "UNkFXeq3jU52", cardID: "UNkFXeq3jU52-2", cardType: CARD_TYPE.TRAP},
    {name: "強制脱出装置", cardURL: "UNkFXeq3jU52", cardID: "UNkFXeq3jU52-3", cardType: CARD_TYPE.TRAP},
    {name: "バージェストマ・オレノイデス", cardURL: "rQx25UiP-bby", cardID: "rQx25UiP-bby-1", cardType: CARD_TYPE.TRAP},
    {name: "バージェストマ・オレノイデス", cardURL: "rQx25UiP-bby", cardID: "rQx25UiP-bby-2", cardType: CARD_TYPE.TRAP},
    {name: "バージェストマ・オレノイデス", cardURL: "rQx25UiP-bby", cardID: "rQx25UiP-bby-3", cardType: CARD_TYPE.TRAP},
    {name: "デモンズ・チェーン", cardURL: "jtCY1XWAGlnS", cardID: "jtCY1XWAGlnS-1", cardType: CARD_TYPE.TRAP},
    {name: "デモンズ・チェーン", cardURL: "jtCY1XWAGlnS", cardID: "jtCY1XWAGlnS-2", cardType: CARD_TYPE.TRAP},
    {name: "デモンズ・チェーン", cardURL: "jtCY1XWAGlnS", cardID: "jtCY1XWAGlnS-3", cardType: CARD_TYPE.TRAP},
    {name: "次元幽閉", cardURL: "7PT3-C0S8wGk", cardID: "7PT3-C0S8wGk-1", cardType: CARD_TYPE.TRAP},
    {name: "次元幽閉", cardURL: "7PT3-C0S8wGk", cardID: "7PT3-C0S8wGk-2", cardType: CARD_TYPE.TRAP},
    {name: "次元幽閉", cardURL: "7PT3-C0S8wGk", cardID: "7PT3-C0S8wGk-3", cardType: CARD_TYPE.TRAP},
    {name: "バージェストマ・ディノミスクス", cardURL: "7T2NIngg8z_k", cardID: "7T2NIngg8z_k-1", cardType: CARD_TYPE.TRAP},
    {name: "バージェストマ・ディノミスクス", cardURL: "7T2NIngg8z_k", cardID: "7T2NIngg8z_k-2", cardType: CARD_TYPE.TRAP},
    {name: "バージェストマ・ディノミスクス", cardURL: "7T2NIngg8z_k", cardID: "7T2NIngg8z_k-3", cardType: CARD_TYPE.TRAP},
    {name: "安全地帯", cardURL: "pPYDErMs4yX2", cardID: "pPYDErMs4yX2-1", cardType: CARD_TYPE.TRAP},
    {name: "安全地帯", cardURL: "pPYDErMs4yX2", cardID: "pPYDErMs4yX2-2", cardType: CARD_TYPE.TRAP},
    {name: "安全地帯", cardURL: "pPYDErMs4yX2", cardID: "pPYDErMs4yX2-3", cardType: CARD_TYPE.TRAP},
    {name: "鳳翼の爆風", cardURL: "JfpPhAURC10l", cardID: "JfpPhAURC10l-1", cardType: CARD_TYPE.TRAP},
    {name: "鳳翼の爆風", cardURL: "JfpPhAURC10l", cardID: "JfpPhAURC10l-2", cardType: CARD_TYPE.TRAP},
    {name: "鳳翼の爆風", cardURL: "JfpPhAURC10l", cardID: "JfpPhAURC10l-3", cardType: CARD_TYPE.TRAP},
    {name: "スキル・サクセサー", cardURL: "U0VC11tAepz2", cardID: "U0VC11tAepz2-1", cardType: CARD_TYPE.TRAP},
    {name: "スキル・サクセサー", cardURL: "U0VC11tAepz2", cardID: "U0VC11tAepz2-2", cardType: CARD_TYPE.TRAP},
    {name: "スキル・サクセサー", cardURL: "U0VC11tAepz2", cardID: "U0VC11tAepz2-3", cardType: CARD_TYPE.TRAP},
    {name: "リビングデッドの呼び声", cardURL: "dWF6ssLJ0s0N", cardID: "dWF6ssLJ0s0N-1", cardType: CARD_TYPE.TRAP},
    {name: "リビングデッドの呼び声", cardURL: "dWF6ssLJ0s0N", cardID: "dWF6ssLJ0s0N-2", cardType: CARD_TYPE.TRAP},
    {name: "リビングデッドの呼び声", cardURL: "dWF6ssLJ0s0N", cardID: "dWF6ssLJ0s0N-3", cardType: CARD_TYPE.TRAP},
    {name: "破壊輪", cardURL: "6NocCRPrTOoX", cardID: "6NocCRPrTOoX-1", cardType: CARD_TYPE.TRAP},
    {name: "破壊輪", cardURL: "6NocCRPrTOoX", cardID: "6NocCRPrTOoX-2", cardType: CARD_TYPE.TRAP},
    {name: "破壊輪", cardURL: "6NocCRPrTOoX", cardID: "6NocCRPrTOoX-3", cardType: CARD_TYPE.TRAP},
    {name: "幻獣の角", cardURL: "mG0Ai07wZktB", cardID: "mG0Ai07wZktB-1", cardType: CARD_TYPE.TRAP},
    {name: "幻獣の角", cardURL: "mG0Ai07wZktB", cardID: "mG0Ai07wZktB-2", cardType: CARD_TYPE.TRAP},
    {name: "幻獣の角", cardURL: "mG0Ai07wZktB", cardID: "mG0Ai07wZktB-3", cardType: CARD_TYPE.TRAP},
    {name: "強化蘇生", cardURL: "ZIXeKGgEF83X", cardID: "ZIXeKGgEF83X-1", cardType: CARD_TYPE.TRAP},
    {name: "強化蘇生", cardURL: "ZIXeKGgEF83X", cardID: "ZIXeKGgEF83X-2", cardType: CARD_TYPE.TRAP},
    {name: "強化蘇生", cardURL: "ZIXeKGgEF83X", cardID: "ZIXeKGgEF83X-3", cardType: CARD_TYPE.TRAP},
    {name: "奈落の落とし穴", cardURL: "vgQdZh5XMwRF", cardID: "vgQdZh5XMwRF-1", cardType: CARD_TYPE.TRAP},
    {name: "奈落の落とし穴", cardURL: "vgQdZh5XMwRF", cardID: "vgQdZh5XMwRF-2", cardType: CARD_TYPE.TRAP},
    {name: "奈落の落とし穴", cardURL: "vgQdZh5XMwRF", cardID: "vgQdZh5XMwRF-3", cardType: CARD_TYPE.TRAP},
    {name: "蟲惑の落とし穴", cardURL: "ko36pCbA8Czk", cardID: "ko36pCbA8Czk-1", cardType: CARD_TYPE.TRAP},
    {name: "蟲惑の落とし穴", cardURL: "ko36pCbA8Czk", cardID: "ko36pCbA8Czk-2", cardType: CARD_TYPE.TRAP},
    {name: "蟲惑の落とし穴", cardURL: "ko36pCbA8Czk", cardID: "ko36pCbA8Czk-3", cardType: CARD_TYPE.TRAP},
    {name: "戦線復帰", cardURL: "8yiW3iVgJCEF", cardID: "8yiW3iVgJCEF-1", cardType: CARD_TYPE.TRAP},
    {name: "戦線復帰", cardURL: "8yiW3iVgJCEF", cardID: "8yiW3iVgJCEF-2", cardType: CARD_TYPE.TRAP},
    {name: "戦線復帰", cardURL: "8yiW3iVgJCEF", cardID: "8yiW3iVgJCEF-3", cardType: CARD_TYPE.TRAP}
  ];

export default TrapCardList;